[[develop]]
= Lab2 Developing a Node.js Application on Openshift
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

[[intro]]
== Introduction

=== What you will learn
In this scenario you will learn more about Node.js,
one of the runtimes included in Red Hat OpenShift Application Runtimes.

You will take an existing sample Node.js application and modify it to address microservice concerns,
understand its structure, deploy it to OpenShift and exercise the interfaces between Node.js apps, microservices, and OpenShift/Kubernetes.

=== Redhat Openshift Nodejs runtime support
Node.js is based on the https://developers.google.com/v8/[V8 JavaScript engine] from Google and allows you to write server-side JavaScript applications.
It provides an I/O model based on events and non-blocking operations that enables you to write applications that are both
lightweight and efficient. Node.js also provides a large module ecosystem called https://www.npmjs.com/[npm].
Check out the https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/node.js_runtime_guide/[Node.js Runtime Guide] for further reading on Node.js and RHOAR.

The Node.js runtime enables you to run Node.js applications and services on OpenShift while providing all the advantages and conveniences of the OpenShift platform such as rolling updates, continuous delivery pipelines, service discovery, and canary deployments. OpenShift also makes it easier for your applications to implement common microservice patterns such as externalized configuration, health check, circuit breaker, and failover.


[[examine-project]]
== Examine the sample project

The sample project shows the components of a Node.js project using Node.js and NPM best practices.

The app implements a simple RESTful microservice which implements a greeting service (that simply returns a Hello greeting).

. Inspect the application code

Click the links below to open each file and inspect its contents:

- link:src/package.json[package.json] - Metadata about the project: name, version, dependencies, and other information needed to build and maintain the project.
- link:src/app.js[app.js] - Main logic of the sample application defining REST endpoints and application runtime configuration.
- link:src/app-config.yml[app-config.yml] - Content used to initially populate the OpenShift ConfigMap, which the sample app will access at runtime.
- link:src/public/index.html[public/index.html] - Simple web UI to access the greeting service.
